### ISSUE TITLE
Quality Issues

### ISSUE THREAD

**Issue by imurreflection** [xbmc-adult/xbmc-adult#171]
Hey Gujal00 bro,  something is wrong with most of the sites in our add-on. Not  sure when it started but it's there now. Most of the sites like xvideos,xhamster and many other picture quality is now completely degraded. We don't see quality selector option and default is 480 p or even lower. Completely unwatchable. It was not there earlier as I have seen some movies in high quality. Example, if we search ' Vintage HD' in xHamster,we get many links but even when on the pc and mobile browser, these links are available as 720 or even 1080p, our add-on plays them in 480p resolution. This is happening in most of the sites though I have checked only above two mentioned.   If you want,I can check all sites to see if this issue is happening across all sites. Kindly check. I will also try to install previous version to see if the issue persists and report you back. Have a great day bro!!!!

**Comment by Gujal00** [comment]
Go to VideoDevil Addon Settings and select the quality you want or set it to "Ask Me"
![Screenshot](https://i.imgur.com/7a9UakD.png)

**Comment by imurreflection** [comment]
Bro, it's already set from the begining . Kindly do above search yourself in xHamster and see if you are getting the quality selector option. I am checking previous versions and will report you back with screenshot

**Comment by Gujal00** [comment]
Yep for XHamster it is using the fallback url which is 144p. Can be fixed.
Which other site is behaving this way?
Xhamster catcher fixed in #170

**Comment by imurreflection** [comment]
Mate, kindly see the Mobile Browser search result from 1st search result on the search term ' Vintage HD' in xHamster . Here you can see the quality selection option but on our add-on it plays default in 480p. No matter if you select the quality selection option as 'High' even. It just does not present any quality selection option even when you select 'ask me'. Please

**Comment by imurreflection** [comment]
So many sites..not sure where things went wrong. Kindly give me some time. I will check all sites and report back. Meanwhile XVideos is down now so I can't check it

**Comment by imurreflection** [comment]
Hey mate, it took me some time to check all 49 sites and here are the observations:

1) Analdin - plays up to 540p only. No Quality Selection
2) Ah Me - Not Working
3) Fux- Not Working
4) Eporner- Not Working
5) Porn HD- Only Low Resolution. No Quality Selection but the site has only HD content. Could be the same issue as xHamster
6)Porn Movies - Only Low Resolution. No Quality Selection
7) Pornoxo - Not Working
8) Vporn- Only Low Resolution. Even in 1080p category and selecting standard in quality, videos plays at a very low resolution.
9) Tnaflix - No Quality Selection. Only 540p
10) Spankwire- Not Working. No Icons
11) Slutload - Not Working
12) Sexu - Only low resolution. Even after selecting High in Quality Selection, plays low resolution.

Please let me know if you need any clarification. Thank  you.

**Comment by Gujal00** [comment]
Ah-me, Spankwire and pornoxo already fixed in #170 
Will take a look at others
No issues found on Eporner, Porn HD and sexu
TNAFlix qualities can't be pulled in videodevil catcher

**Comment by imurreflection** [comment]
Thank you mate. Please let me know how can I download #170 as there is no update available. The current version is 1.7.204.

**Comment by Gujal00** [comment]
Yep have to wait for @mrdougquaid to release it. Otherwise you can look at the PR #170 and download each of the files manually and replace them in your system. only for the technically inclined!

**Comment by imurreflection** [comment]
Ah..this indeed sounds technical. Though, I am capable of doing it,  I would rather like to wait for mrdougquaid to release it. Thanks for the help mate. Have a nice day

**Comment by imurreflection** [comment]
@Gujal00 Mate, at the time of checking, these issues persists. However, PornHd still has the reported issue as all videos are playing with very low resolution. There is no Quality Selection option available.. These videos are available in HD on Mobile and PC web browsers. Thank You

**Comment by Gujal00** [comment]
> @Gujal00 Mate, at the time of checking, these issues persists. However, PornHd still has the reported issue as all videos are playing with very low resolution. There is no Quality Selection option available.. These videos are available in HD on Mobile and PC web browsers. Thank You

PornHD shows 3 qualities for most vids and plays 720p fine. May be some sort of isp restriction or vpn on your end

**Comment by imurreflection** [comment]
Yes, you are right bro. Site is working fine on VPN.

**Comment by imurreflection** [comment]
Hello @mrdougquaid, may I request you to release the latest version please

**Comment by imurreflection** [comment]
Hi, most issues are fixed in #170 and #171 but the new update has not been released. Kindly release the new version @mrdougquaid

**Comment by Gujal00** [comment]
Please close the issue as all the sites with multiple qualities are fixed
